name: "Test Nim"
on:
  push:
    paths:
      - "ejemplos/nim/**"
  pull_request:
    paths:
      - "ejemplos/nim/**"

jobs:
  test-nim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.4.0' # default is 'stable'
      - run: cd ejemplos/nim && nimble build -Y
      - run: cd ejemplos/nim && nimble test -Y

